# This YAML configuration file defines specific domains and their DNS behaviors.
# For 'static' behavior, the DNS server always returns the static IP defined here
# For 'once' behavior, the DNS server first returns Google's DNS response, then always the static IP for subsequent requests
# For 'flip' behavior, the DNS server alternates between Google's DNS response and the static IP for each request


specific_domains:
- domain: 'example.com'
  ip: '1.2.3.4'
  behavior: 'static'  # Always returns 1.2.3.4 for example.com

- domain: 'nginx.org'
  ip: '127.0.0.1'
  behavior: 'once'  # Returns Google's DNS response first time, then 5.6.7.8 afterwards

- domain: 'google.com'
  ip: '9.10.11.12'
  behavior: 'flip'  # Alternates between Google's DNS response and 9.10.11.12 for each request
